name: Build

on:
  workflow_dispatch:
    inputs:
      build:
        description: "what to build"
        required: true
      args:
        description: "args passed to build-*.sh"
        required: false
      skip-installing-deps:
        description: "skip installing deps (for debugging only)"
        required: false
        type: boolean

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    strategy:
      matrix: 
        base-image: [raspios_lite, raspios_lite_arm64]
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Building
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: ${{ matrix.base-image }}:2022-04-04
          copy_repository_path: /root-repo
          copy_artifact_path: artifacts
          copy_artifact_dest: ~/artifacts

          shell: /bin/bash
          command: |
            mkdir -p ~/artifacts
            ############################
            sudo apt-get update -qy
            sudo apt-get install curl git -qy
            if ! ${{ github.event.inputs.skip-installing-deps }}; then
              sudo apt-get install build-essential -qy
            fi
            ############################
            cd /root-repo && \
              bash scripts/build-${{ github.event.inputs.build }}.sh ${{ github.event.inputs.args }}



#       uses: uraimo/run-on-arch-action@v2.5.0
#       with:
#         arch: ${{ matrix.arch }}
#         distro: bullseye
#
#         githubToken: ${{ github.token }}
#
#         setup: |
#           mkdir -p ~/artifacts
#
#         dockerRunArgs: |
#           --volume "$HOME/artifacts:/artifacts"
#           --volume "$HOME/work/build-things/build-things:/root-repo"
#
#         shell: /bin/bash
#
#         install: |
#           apt-get update -qy
#           apt-get install curl git -qy
#
#           if ! ${{ github.event.inputs.skip-installing-deps }}; then
#             apt-get install build-essential -qy
#           fi
#
#         run: |
#           cd /root-repo && bash scripts/build-${{ github.event.inputs.build }}.sh ${{ github.event.inputs.args }}
                
      - name: Upload build result(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.build }}-${{ matrix.arch }}
          path: ~/artifacts
