name: Build

on:
  workflow_dispatch:
    inputs:
      build:
        description: "what to build"
        required: true
      args:
        description: "args passed to build-*.sh"
        required: false
      skip-installing-deps:
        description: "skip installing deps (for debugging only)"
        required: false
        type: boolean

jobs:
  build:
    name: building ${{ github.event.inputs.build }} (${{ matrix.arch }})
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    strategy:
      matrix: 
        arch: [armv7, aarch64]
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Building
        uses: uraimo/run-on-arch-action@v2.5.0
        with:
          arch: ${{ matrix.arch }}
          distro: bullseye
 
          githubToken: ${{ github.token }}
 
          setup: |
            mkdir -p ~/artifacts
 
          dockerRunArgs: |
            --volume "$HOME/artifacts:/artifacts"
            --volume "$HOME/work/build-things/build-things:/build-things"
 
          shell: /bin/bash
 
          install: |
            apt-get update -qy
            apt-get install curl git -qy
 
            if ! ${{ github.event.inputs.skip-installing-deps }}; then
              apt-get install build-essential -qy
              
              git clone https://github.com/UrNightmaree/build-things
              [[ -e build-things/scripts/install-deps-${{ github.event.inputs.build }}.sh ]] &&
                cd build-things && bash scripts/install-deps-${{ github.event.inputs.build }}.sh
            fi
 
          run: |
            cd /build-things && bash scripts/build-${{ github.event.inputs.build }}.sh ${{ github.event.inputs.args }}
                
      - name: Upload build result(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.build }}-${{ matrix.arch }}
          path: ~/artifacts
