name: Build v2

on:
  workflow_dispatch:
    inputs:
      build:
        description: "what to build"
        required: true
      args:
        description: "args passed to build-*.sh"
        required: false
      skip-installing-deps:
        description: "skip installing deps (for debugging only)"
        required: false
        type: boolean

jobs:
  build:
    name: building ${{ github.event.inputs.build }} (${{ matrix.image }})
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: 
        image: [raspios_lite, raspios_lite_arm64]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Building
        id: building
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: ${{ matrix.image }}:2022-04-04
          shell: /bin/bash
          bind_mount_repository: true
          copy_repository_path: /opt/repo
          copy_artifact_path: artifacts
          copy_artifact_dest: $HOME/artifacts
          image_additional_mb: 4096
          commands: |
            # fix $HOME being no file or directory
            mkdir $HOME || printf '\x1b[1m$HOME exist!\x1b[0m\n'

            mkdir -p artifacts
            sudo apt-get update
            sudo apt-get install curl git -qy --no-install-recommends

            if ! ${{ github.event.inputs.skip-installing-deps }}; then
              [[ -e scripts/install-deps-${{ github.event.inputs.build }}.sh ]] &&
                bash scripts/install-deps-${{ github.event.inputs.build }}.sh
            fi

            ARTIFACTS=/opt/repo/artifacts bash scripts/build-${{ github.event.inputs.build }}.sh


      - name: Upload build result(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.build }}-${{ matrix.image }}
          path: ~/artifacts
