name: Build

on:
  workflow_dispatch:
    inputs:
      build:
        description: "what to build"
        required: true
      args:
        description: "args passed to build-*.sh"
        required: false

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    strategy:
      matrix: 
        arch: [armv7, aarch64]
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Building
        uses: uraimo/run-on-arch-action@v2.5.0
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu22.04

          githubToken: ${{ github.token }}

          setup: |
            mkdir -p ~/artifacts

          dockerRunArgs: |
            --volume "$HOME/artifacts:/artifacts"
            --volume "$HOME/work/build-things/build-things:/root-repo"

          shell: /bin/sh

          install: |
            apt-get update -qy
            apt install build-essential git curl sudo -qy

          run: |
            cd /root-repo && bash scripts/build-${{ github.event.inputs.build }}.sh ${{ github.event.inputs.args }}
                  
      - name: Upload build result(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.build }}-${{ matrix.arch }}
          path: ~/artifacts
