name: Build

on:
  workflow_dispatch:
    inputs:
      build:
        description: "what to build"
        required: true
      args:
        description: "args passed to build-*.sh"
        required: false

jobs:
  build:
    name: Building ${{ github.event.inputs.build }} for ${{ matrix.target_arch }}
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    strategy:
      matrix: 
        target_arch: [aarch64, armv7]
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Building
        uses: uraimo/run-on-arch-action@v2.5.0
        with:
          arch: ${{ matrix.target_arch }}
          distro: ubuntu22.04

          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "/home/runner/artifacts"

          dockerRunArgs: |
            --volume "/home/runner/artifacts:/artifacts"

          shell: /bin/sh

          install: |
            apt-get update -qy
            apt-get install bash libgmp-dev libmpfr-dev libgtk-3-dev libwebkit2gtk-4.0-dev -qy

          run: |
            bash scripts/build-${{ github.event.inputs.build }} ${{ github.event.inputs.args }}

      - name: Upload build result(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.build }}-${{ matrix.target_arch }}
          path: /home/runner/artifacts
