name: Build

on:
  workflow_dispatch:
    inputs:
      build:
        description: "what to build"
        required: true
      args:
        description: "args passed to build-*.sh"
        required: false

jobs:
  build:
    name: Building ${{ github.event.inputs.build }} for ${{ matrix.arch }}
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    strategy:
      matrix: 
        arch: [arm, arm64]
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

      - name: Building
        run: |
          mkdir ~/artifacts -p
          bash scripts/build-${{ github.event.inputs.build }}.sh ${{ github.event.inputs.args }}
        
      - name: Upload build result(s) as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.build }}-${{ matrix.arch }}
          path: ~/artifacts
